/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_erp;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static school_erp.DbConnector.con;

/**
 *
 * @author Ashu
 */
public class EditStudents extends javax.swing.JFrame {

    /**
     * Creates new form EditStudents
     */
    public EditStudents() {
        initComponents();
        setLocation(400,120);
    }
    public EditStudents(String sid)
    {
        initComponents();
        setLocation(400,120);
        //databse connection 
        //DbConnector dbc = new DbConnector();
        //dbc.Connection();
        try
        {
            Statement st = con.createStatement();
            String query = "Select * from `stu_reg` WHERE `id`='"+sid+"'";

            ResultSet rs = st.executeQuery(query);
            if(rs.next())
                {
                    String s_id =rs.getString(1);
                    String s_name =rs.getString(2);
                    String f_name =rs.getString(3);
                    String s_phone =rs.getString(4);
                    String f_phone =rs.getString(5);
                    String s_class =rs.getString(6);
                    String s_roll =rs.getString(7);
                    String s_add =rs.getString(8);
                    
                    
                    
                    Sid.setText(s_id);
                    Sname.setText(s_name);
                    Sfather.setText(f_name);
                    Sphone.setText(s_phone);
                    Sfatherphone.setText(f_phone);
                    Sclass.setText(s_class);
                    Sroll.setText(s_roll);
                    Saddress.setText(s_add);
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No Data Found!");
                }
            JOptionPane.showMessageDialog(null, "Data Fetched Successfully!");
            
           
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Sname = new javax.swing.JTextField();
        Sfather = new javax.swing.JTextField();
        Sphone = new javax.swing.JTextField();
        Sfatherphone = new javax.swing.JTextField();
        Sclass = new javax.swing.JTextField();
        Sroll = new javax.swing.JTextField();
        Saddress = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Sid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Updation Of Records", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Rename Father :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 140, 120, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Change Phone :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 184, 120, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Father Phone  : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 228, 120, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Change Class :");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 272, 120, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Change Roll No. : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 315, 120, 25));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Change Address :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 358, 120, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Rename : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 96, 120, 25));
        jPanel1.add(Sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 97, 177, 25));
        jPanel1.add(Sfather, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 141, 177, 25));
        jPanel1.add(Sphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 185, 177, 25));
        jPanel1.add(Sfatherphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 229, 177, 25));
        jPanel1.add(Sclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 275, 177, -1));
        jPanel1.add(Sroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 318, 177, -1));

        Saddress.setToolTipText("");
        jPanel1.add(Saddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 361, 177, -1));

        submit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 401, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Back");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 30, 59, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 61, -1, -1));

        Sid.setEditable(false);
        Sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SidActionPerformed(evt);
            }
        });
        jPanel1.add(Sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 58, 177, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 401, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String id = Sid.getText();
        String name = Sname.getText();
        String fname = Sfather.getText();
        String phone = Sphone.getText();
        String Fphone = Sfatherphone.getText();
        String Class = Sclass.getText();
        String roll = Sroll.getText();
        String add = Saddress.getText();
        
         try 
        {
            Statement st = con.createStatement();
            String query = "UPDATE `stu_reg` SET `name`='"+name+"',`fname`='"+fname+"',`phone`='"+phone+"',`fphone`='"+Fphone+"',`class`='"+Class+"',`roll`='"+roll+"',`address`='"+add+"' WHERE `id`='"+id+"'";
            
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Record Updated Successfully!");    
            
            Sid.setText("");
            Sname.setText("");
            Sfather.setText("");
            Sphone.setText("");
            Sfatherphone.setText("");
            Sclass.setText("");
            Sroll.setText("");
            Saddress.setText("");
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        studentsmodule sm = new studentsmodule();
        sm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void SidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Sid.setText("");
        Sname.setText("");
        Sfather.setText("");
        Sphone.setText("");
        Sfatherphone.setText("");
        Sclass.setText("");
        Sroll.setText("");
        Saddress.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Saddress;
    private javax.swing.JTextField Sclass;
    private javax.swing.JTextField Sfather;
    private javax.swing.JTextField Sfatherphone;
    private javax.swing.JTextField Sid;
    private javax.swing.JTextField Sname;
    private javax.swing.JTextField Sphone;
    private javax.swing.JTextField Sroll;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
